root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/worker ./cmd/worker"
  bin = "./tmp/worker"
  delay = 500
  exclude_dir = ["tmp", "bin", "docs", "database/sqlc", "database/migrations", "testdata"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_dir = ["cmd/worker", "internal", "pkg"]
  include_ext = ["go"]
  kill_delay = "500ms"
  log = "tmp/build-worker.log"
  rerun = false
  send_interrupt = true
  stop_on_error = true

[color]
  build  = "yellow"
  main   = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
