// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (id, workspace_id, name, type, encrypted_data, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, workspace_id, name, type, encrypted_data, created_at
`

type CreateCredentialParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceID   string      `json:"workspace_id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	EncryptedData []byte      `json:"encrypted_data"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.EncryptedData,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.EncryptedData,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials
WHERE id = $1 AND workspace_id = $2
`

type DeleteCredentialParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.WorkspaceID)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, workspace_id, name, type, encrypted_data, created_at FROM credentials
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetCredentialParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.ID, arg.WorkspaceID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.EncryptedData,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, workspace_id, name, type, encrypted_data, created_at FROM credentials
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCredentials(ctx context.Context, workspaceID string) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.EncryptedData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
