// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: datatables.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDataTable = `-- name: CreateDataTable :one
INSERT INTO data_tables (id, workspace_id, name, schema, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, workspace_id, name, schema, created_at
`

type CreateDataTableParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	Name        string      `json:"name"`
	Schema      []byte      `json:"schema"`
}

func (q *Queries) CreateDataTable(ctx context.Context, arg CreateDataTableParams) (DataTable, error) {
	row := q.db.QueryRow(ctx, createDataTable,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Schema,
	)
	var i DataTable
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Schema,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDataTable = `-- name: DeleteDataTable :exec
DELETE FROM data_tables
WHERE id = $1 AND workspace_id = $2
`

type DeleteDataTableParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) DeleteDataTable(ctx context.Context, arg DeleteDataTableParams) error {
	_, err := q.db.Exec(ctx, deleteDataTable, arg.ID, arg.WorkspaceID)
	return err
}

const deleteDataTableRow = `-- name: DeleteDataTableRow :exec
DELETE FROM data_table_rows
WHERE id = $1 AND table_id = $2 AND workspace_id = $3
`

type DeleteDataTableRowParams struct {
	ID          pgtype.UUID `json:"id"`
	TableID     pgtype.UUID `json:"table_id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) DeleteDataTableRow(ctx context.Context, arg DeleteDataTableRowParams) error {
	_, err := q.db.Exec(ctx, deleteDataTableRow, arg.ID, arg.TableID, arg.WorkspaceID)
	return err
}

const getDataTable = `-- name: GetDataTable :one
SELECT id, workspace_id, name, schema, created_at FROM data_tables
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetDataTableParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) GetDataTable(ctx context.Context, arg GetDataTableParams) (DataTable, error) {
	row := q.db.QueryRow(ctx, getDataTable, arg.ID, arg.WorkspaceID)
	var i DataTable
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Schema,
		&i.CreatedAt,
	)
	return i, err
}

const insertDataTableRow = `-- name: InsertDataTableRow :one
INSERT INTO data_table_rows (id, table_id, workspace_id, data, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, table_id, workspace_id, data, created_at, updated_at
`

type InsertDataTableRowParams struct {
	ID          pgtype.UUID `json:"id"`
	TableID     pgtype.UUID `json:"table_id"`
	WorkspaceID string      `json:"workspace_id"`
	Data        []byte      `json:"data"`
}

func (q *Queries) InsertDataTableRow(ctx context.Context, arg InsertDataTableRowParams) (DataTableRow, error) {
	row := q.db.QueryRow(ctx, insertDataTableRow,
		arg.ID,
		arg.TableID,
		arg.WorkspaceID,
		arg.Data,
	)
	var i DataTableRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.WorkspaceID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataTableRows = `-- name: ListDataTableRows :many
SELECT id, table_id, workspace_id, data, created_at, updated_at FROM data_table_rows
WHERE table_id = $1 AND workspace_id = $2
ORDER BY created_at DESC
LIMIT 1000
`

type ListDataTableRowsParams struct {
	TableID     pgtype.UUID `json:"table_id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) ListDataTableRows(ctx context.Context, arg ListDataTableRowsParams) ([]DataTableRow, error) {
	rows, err := q.db.Query(ctx, listDataTableRows, arg.TableID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataTableRow{}
	for rows.Next() {
		var i DataTableRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.WorkspaceID,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataTables = `-- name: ListDataTables :many
SELECT id, workspace_id, name, schema, created_at FROM data_tables
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDataTables(ctx context.Context, workspaceID string) ([]DataTable, error) {
	rows, err := q.db.Query(ctx, listDataTables, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataTable{}
	for rows.Next() {
		var i DataTable
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Schema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
