// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelExecution = `-- name: CancelExecution :one
UPDATE executions
SET status = 'cancelled'
WHERE id = $1 AND workspace_id = $2 AND status IN ('pending', 'queued')
RETURNING id, workspace_id, workflow_id, workflow_version_id, status, trigger_source, started_at, finished_at, input, output, error, created_at
`

type CancelExecutionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) CancelExecution(ctx context.Context, arg CancelExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, cancelExecution, arg.ID, arg.WorkspaceID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerSource,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (
    id, workspace_id, workflow_id, workflow_version_id,
    status, trigger_source, input, created_at
)
VALUES ($1, $2, $3, $4, 'queued', $5, $6, now())
RETURNING id, workspace_id, workflow_id, workflow_version_id, status, trigger_source, started_at, finished_at, input, output, error, created_at
`

type CreateExecutionParams struct {
	ID                pgtype.UUID `json:"id"`
	WorkspaceID       string      `json:"workspace_id"`
	WorkflowID        pgtype.UUID `json:"workflow_id"`
	WorkflowVersionID pgtype.UUID `json:"workflow_version_id"`
	TriggerSource     *string     `json:"trigger_source"`
	Input             []byte      `json:"input"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.ID,
		arg.WorkspaceID,
		arg.WorkflowID,
		arg.WorkflowVersionID,
		arg.TriggerSource,
		arg.Input,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerSource,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createExecutionLog = `-- name: CreateExecutionLog :exec
INSERT INTO execution_logs (execution_id, node_id, level, message, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type CreateExecutionLogParams struct {
	ExecutionID pgtype.UUID `json:"execution_id"`
	NodeID      *string     `json:"node_id"`
	Level       string      `json:"level"`
	Message     string      `json:"message"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateExecutionLog(ctx context.Context, arg CreateExecutionLogParams) error {
	_, err := q.db.Exec(ctx, createExecutionLog,
		arg.ExecutionID,
		arg.NodeID,
		arg.Level,
		arg.Message,
		arg.Metadata,
	)
	return err
}

const finishExecution = `-- name: FinishExecution :exec
UPDATE executions
SET status = $2, finished_at = now(), output = $3, error = $4
WHERE id = $1
`

type FinishExecutionParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	Output []byte      `json:"output"`
	Error  *string     `json:"error"`
}

func (q *Queries) FinishExecution(ctx context.Context, arg FinishExecutionParams) error {
	_, err := q.db.Exec(ctx, finishExecution,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.Error,
	)
	return err
}

const getExecution = `-- name: GetExecution :one
SELECT id, workspace_id, workflow_id, workflow_version_id, status, trigger_source, started_at, finished_at, input, output, error, created_at FROM executions
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetExecutionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.ID, arg.WorkspaceID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerSource,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionInternal = `-- name: GetExecutionInternal :one
SELECT id, workspace_id, workflow_id, workflow_version_id, status, trigger_source, started_at, finished_at, input, output, error, created_at FROM executions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetExecutionInternal(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionInternal, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerSource,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutionLogs = `-- name: ListExecutionLogs :many
SELECT id, execution_id, node_id, level, message, metadata, created_at FROM execution_logs
WHERE execution_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListExecutionLogs(ctx context.Context, executionID pgtype.UUID) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, listExecutionLogs, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.NodeID,
			&i.Level,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByWorkflow = `-- name: ListExecutionsByWorkflow :many
SELECT id, workspace_id, workflow_id, workflow_version_id, status, trigger_source, started_at, finished_at, input, output, error, created_at FROM executions
WHERE workflow_id = $1 AND workspace_id = $2
ORDER BY created_at DESC
`

type ListExecutionsByWorkflowParams struct {
	WorkflowID  pgtype.UUID `json:"workflow_id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) ListExecutionsByWorkflow(ctx context.Context, arg ListExecutionsByWorkflowParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutionsByWorkflow, arg.WorkflowID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.Status,
			&i.TriggerSource,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Input,
			&i.Output,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByWorkspace = `-- name: ListExecutionsByWorkspace :many
SELECT id, workspace_id, workflow_id, workflow_version_id, status, trigger_source, started_at, finished_at, input, output, error, created_at FROM executions
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListExecutionsByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListExecutionsByWorkspace(ctx context.Context, arg ListExecutionsByWorkspaceParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutionsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.Status,
			&i.TriggerSource,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Input,
			&i.Output,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startExecution = `-- name: StartExecution :exec
UPDATE executions
SET status = 'running', started_at = now()
WHERE id = $1
`

func (q *Queries) StartExecution(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startExecution, id)
	return err
}
