// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          pgtype.UUID      `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	KeyHash     string           `json:"key_hash"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Credential struct {
	ID            pgtype.UUID      `json:"id"`
	WorkspaceID   string           `json:"workspace_id"`
	Name          string           `json:"name"`
	Type          string           `json:"type"`
	EncryptedData []byte           `json:"encrypted_data"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type DataTable struct {
	ID          pgtype.UUID      `json:"id"`
	WorkspaceID string           `json:"workspace_id"`
	Name        string           `json:"name"`
	Schema      []byte           `json:"schema"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type DataTableRow struct {
	ID          pgtype.UUID      `json:"id"`
	TableID     pgtype.UUID      `json:"table_id"`
	WorkspaceID string           `json:"workspace_id"`
	Data        []byte           `json:"data"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Execution struct {
	ID                pgtype.UUID      `json:"id"`
	WorkspaceID       string           `json:"workspace_id"`
	WorkflowID        pgtype.UUID      `json:"workflow_id"`
	WorkflowVersionID pgtype.UUID      `json:"workflow_version_id"`
	Status            string           `json:"status"`
	TriggerSource     *string          `json:"trigger_source"`
	StartedAt         pgtype.Timestamp `json:"started_at"`
	FinishedAt        pgtype.Timestamp `json:"finished_at"`
	Input             []byte           `json:"input"`
	Output            []byte           `json:"output"`
	Error             *string          `json:"error"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type ExecutionLog struct {
	ID          int64            `json:"id"`
	ExecutionID pgtype.UUID      `json:"execution_id"`
	NodeID      *string          `json:"node_id"`
	Level       string           `json:"level"`
	Message     string           `json:"message"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type NodeType struct {
	ID              pgtype.UUID      `json:"id"`
	WorkspaceID     string           `json:"workspace_id"`
	Name            string           `json:"name"`
	Description     *string          `json:"description"`
	Category        string           `json:"category"`
	Version         string           `json:"version"`
	BaseUrl         string           `json:"base_url"`
	Endpoint        string           `json:"endpoint"`
	Method          string           `json:"method"`
	ContentType     string           `json:"content_type"`
	HeadersTemplate []byte           `json:"headers_template"`
	BodyTemplate    *string          `json:"body_template"`
	InputSchema     []byte           `json:"input_schema"`
	OutputSchema    []byte           `json:"output_schema"`
	CredentialID    pgtype.UUID      `json:"credential_id"`
	Active          bool             `json:"active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Workflow struct {
	ID            pgtype.UUID      `json:"id"`
	WorkspaceID   string           `json:"workspace_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	Active        bool             `json:"active"`
	LatestVersion int32            `json:"latest_version"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	WebhookSecret *string          `json:"webhook_secret"`
}

type WorkflowVersion struct {
	ID         pgtype.UUID      `json:"id"`
	WorkflowID pgtype.UUID      `json:"workflow_id"`
	Version    int32            `json:"version"`
	Definition []byte           `json:"definition"`
	Published  bool             `json:"published"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
