// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeType = `-- name: CreateNodeType :one
INSERT INTO node_types (
    id, workspace_id, name, description, category, version,
    base_url, endpoint, method, content_type,
    headers_template, body_template,
    input_schema, output_schema,
    credential_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12,
    $13, $14,
    $15, now(), now()
) RETURNING id, workspace_id, name, description, category, version, base_url, endpoint, method, content_type, headers_template, body_template, input_schema, output_schema, credential_id, active, created_at, updated_at
`

type CreateNodeTypeParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     string      `json:"workspace_id"`
	Name            string      `json:"name"`
	Description     *string     `json:"description"`
	Category        string      `json:"category"`
	Version         string      `json:"version"`
	BaseUrl         string      `json:"base_url"`
	Endpoint        string      `json:"endpoint"`
	Method          string      `json:"method"`
	ContentType     string      `json:"content_type"`
	HeadersTemplate []byte      `json:"headers_template"`
	BodyTemplate    *string     `json:"body_template"`
	InputSchema     []byte      `json:"input_schema"`
	OutputSchema    []byte      `json:"output_schema"`
	CredentialID    pgtype.UUID `json:"credential_id"`
}

func (q *Queries) CreateNodeType(ctx context.Context, arg CreateNodeTypeParams) (NodeType, error) {
	row := q.db.QueryRow(ctx, createNodeType,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Version,
		arg.BaseUrl,
		arg.Endpoint,
		arg.Method,
		arg.ContentType,
		arg.HeadersTemplate,
		arg.BodyTemplate,
		arg.InputSchema,
		arg.OutputSchema,
		arg.CredentialID,
	)
	var i NodeType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.BaseUrl,
		&i.Endpoint,
		&i.Method,
		&i.ContentType,
		&i.HeadersTemplate,
		&i.BodyTemplate,
		&i.InputSchema,
		&i.OutputSchema,
		&i.CredentialID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNodeType = `-- name: DeleteNodeType :exec
DELETE FROM node_types
WHERE id = $1 AND workspace_id = $2
`

type DeleteNodeTypeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) DeleteNodeType(ctx context.Context, arg DeleteNodeTypeParams) error {
	_, err := q.db.Exec(ctx, deleteNodeType, arg.ID, arg.WorkspaceID)
	return err
}

const getNodeType = `-- name: GetNodeType :one
SELECT id, workspace_id, name, description, category, version, base_url, endpoint, method, content_type, headers_template, body_template, input_schema, output_schema, credential_id, active, created_at, updated_at FROM node_types
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetNodeTypeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) GetNodeType(ctx context.Context, arg GetNodeTypeParams) (NodeType, error) {
	row := q.db.QueryRow(ctx, getNodeType, arg.ID, arg.WorkspaceID)
	var i NodeType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.BaseUrl,
		&i.Endpoint,
		&i.Method,
		&i.ContentType,
		&i.HeadersTemplate,
		&i.BodyTemplate,
		&i.InputSchema,
		&i.OutputSchema,
		&i.CredentialID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeTypeByID = `-- name: GetNodeTypeByID :one
SELECT id, workspace_id, name, description, category, version, base_url, endpoint, method, content_type, headers_template, body_template, input_schema, output_schema, credential_id, active, created_at, updated_at FROM node_types
WHERE id = $1 AND active = true
LIMIT 1
`

func (q *Queries) GetNodeTypeByID(ctx context.Context, id pgtype.UUID) (NodeType, error) {
	row := q.db.QueryRow(ctx, getNodeTypeByID, id)
	var i NodeType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.BaseUrl,
		&i.Endpoint,
		&i.Method,
		&i.ContentType,
		&i.HeadersTemplate,
		&i.BodyTemplate,
		&i.InputSchema,
		&i.OutputSchema,
		&i.CredentialID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodeTypes = `-- name: ListNodeTypes :many
SELECT id, workspace_id, name, description, category, version, base_url, endpoint, method, content_type, headers_template, body_template, input_schema, output_schema, credential_id, active, created_at, updated_at FROM node_types
WHERE workspace_id = $1
  AND active = true
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%' OR description ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR category = $3)
ORDER BY name ASC
`

type ListNodeTypesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Column2     string `json:"column_2"`
	Column3     string `json:"column_3"`
}

func (q *Queries) ListNodeTypes(ctx context.Context, arg ListNodeTypesParams) ([]NodeType, error) {
	rows, err := q.db.Query(ctx, listNodeTypes, arg.WorkspaceID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeType{}
	for rows.Next() {
		var i NodeType
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Version,
			&i.BaseUrl,
			&i.Endpoint,
			&i.Method,
			&i.ContentType,
			&i.HeadersTemplate,
			&i.BodyTemplate,
			&i.InputSchema,
			&i.OutputSchema,
			&i.CredentialID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeType = `-- name: UpdateNodeType :one
UPDATE node_types SET
    name             = $3,
    description      = $4,
    category         = $5,
    base_url         = $6,
    endpoint         = $7,
    method           = $8,
    content_type     = $9,
    headers_template = $10,
    body_template    = $11,
    input_schema     = $12,
    output_schema    = $13,
    credential_id    = $14,
    updated_at       = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, description, category, version, base_url, endpoint, method, content_type, headers_template, body_template, input_schema, output_schema, credential_id, active, created_at, updated_at
`

type UpdateNodeTypeParams struct {
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     string      `json:"workspace_id"`
	Name            string      `json:"name"`
	Description     *string     `json:"description"`
	Category        string      `json:"category"`
	BaseUrl         string      `json:"base_url"`
	Endpoint        string      `json:"endpoint"`
	Method          string      `json:"method"`
	ContentType     string      `json:"content_type"`
	HeadersTemplate []byte      `json:"headers_template"`
	BodyTemplate    *string     `json:"body_template"`
	InputSchema     []byte      `json:"input_schema"`
	OutputSchema    []byte      `json:"output_schema"`
	CredentialID    pgtype.UUID `json:"credential_id"`
}

func (q *Queries) UpdateNodeType(ctx context.Context, arg UpdateNodeTypeParams) (NodeType, error) {
	row := q.db.QueryRow(ctx, updateNodeType,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.BaseUrl,
		arg.Endpoint,
		arg.Method,
		arg.ContentType,
		arg.HeadersTemplate,
		arg.BodyTemplate,
		arg.InputSchema,
		arg.OutputSchema,
		arg.CredentialID,
	)
	var i NodeType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.BaseUrl,
		&i.Endpoint,
		&i.Method,
		&i.ContentType,
		&i.HeadersTemplate,
		&i.BodyTemplate,
		&i.InputSchema,
		&i.OutputSchema,
		&i.CredentialID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
