// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpWorkflowVersion = `-- name: BumpWorkflowVersion :one
UPDATE workflows
SET latest_version = latest_version + 1, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret
`

type BumpWorkflowVersionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) BumpWorkflowVersion(ctx context.Context, arg BumpWorkflowVersionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, bumpWorkflowVersion, arg.ID, arg.WorkspaceID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (id, workspace_id, name, description, active, latest_version, created_at, updated_at)
VALUES ($1, $2, $3, $4, false, 1, now(), now())
RETURNING id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret
`

type CreateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO workflow_versions (id, workflow_id, version, definition, published, created_at)
VALUES ($1, $2, $3, $4, false, now())
RETURNING id, workflow_id, version, definition, published, created_at
`

type CreateWorkflowVersionParams struct {
	ID         pgtype.UUID `json:"id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Version    int32       `json:"version"`
	Definition []byte      `json:"definition"`
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion,
		arg.ID,
		arg.WorkflowID,
		arg.Version,
		arg.Definition,
	)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Definition,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, arg.ID, arg.WorkspaceID)
	return err
}

const getLatestPublishedVersion = `-- name: GetLatestPublishedVersion :one
SELECT id, workflow_id, version, definition, published, created_at FROM workflow_versions
WHERE workflow_id = $1 AND published = true
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestPublishedVersion(ctx context.Context, workflowID pgtype.UUID) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getLatestPublishedVersion, workflowID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Definition,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret FROM workflows
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.WorkspaceID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}

const getWorkflowByWebhookSecret = `-- name: GetWorkflowByWebhookSecret :one
SELECT id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret FROM workflows
WHERE id = $1 AND webhook_secret = $2 AND active = true
LIMIT 1
`

type GetWorkflowByWebhookSecretParams struct {
	ID            pgtype.UUID `json:"id"`
	WebhookSecret *string     `json:"webhook_secret"`
}

func (q *Queries) GetWorkflowByWebhookSecret(ctx context.Context, arg GetWorkflowByWebhookSecretParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByWebhookSecret, arg.ID, arg.WebhookSecret)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}

const getWorkflowVersion = `-- name: GetWorkflowVersion :one
SELECT id, workflow_id, version, definition, published, created_at FROM workflow_versions
WHERE id = $1 AND workflow_id = $2
LIMIT 1
`

type GetWorkflowVersionParams struct {
	ID         pgtype.UUID `json:"id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) GetWorkflowVersion(ctx context.Context, arg GetWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersion, arg.ID, arg.WorkflowID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Definition,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowVersionByID = `-- name: GetWorkflowVersionByID :one
SELECT id, workflow_id, version, definition, published, created_at FROM workflow_versions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWorkflowVersionByID(ctx context.Context, id pgtype.UUID) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByID, id)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Definition,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowVersionByNumber = `-- name: GetWorkflowVersionByNumber :one
SELECT id, workflow_id, version, definition, published, created_at FROM workflow_versions
WHERE workflow_id = $1 AND version = $2
LIMIT 1
`

type GetWorkflowVersionByNumberParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Version    int32       `json:"version"`
}

func (q *Queries) GetWorkflowVersionByNumber(ctx context.Context, arg GetWorkflowVersionByNumberParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByNumber, arg.WorkflowID, arg.Version)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Definition,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkflowVersions = `-- name: ListWorkflowVersions :many
SELECT id, workflow_id, version, definition, published, created_at FROM workflow_versions
WHERE workflow_id = $1
ORDER BY version DESC
`

func (q *Queries) ListWorkflowVersions(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersions, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowVersion{}
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Version,
			&i.Definition,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret FROM workflows
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context, workspaceID string) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.LatestVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishWorkflowVersion = `-- name: PublishWorkflowVersion :one
UPDATE workflow_versions
SET published = true
WHERE id = $1 AND workflow_id = $2
RETURNING id, workflow_id, version, definition, published, created_at
`

type PublishWorkflowVersionParams struct {
	ID         pgtype.UUID `json:"id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) PublishWorkflowVersion(ctx context.Context, arg PublishWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, publishWorkflowVersion, arg.ID, arg.WorkflowID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.Definition,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const setWebhookSecret = `-- name: SetWebhookSecret :one
UPDATE workflows
SET webhook_secret = $3
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret
`

type SetWebhookSecretParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceID   string      `json:"workspace_id"`
	WebhookSecret *string     `json:"webhook_secret"`
}

func (q *Queries) SetWebhookSecret(ctx context.Context, arg SetWebhookSecretParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, setWebhookSecret, arg.ID, arg.WorkspaceID, arg.WebhookSecret)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}

const setWorkflowActive = `-- name: SetWorkflowActive :one
UPDATE workflows
SET active = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret
`

type SetWorkflowActiveParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	Active      bool        `json:"active"`
}

func (q *Queries) SetWorkflowActive(ctx context.Context, arg SetWorkflowActiveParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, setWorkflowActive, arg.ID, arg.WorkspaceID, arg.Active)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name = $3, description = $4, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, description, active, latest_version, created_at, updated_at, webhook_secret
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
	)
	return i, err
}
